name: Deploy app
env:
  APP_PATH: /var/app/etherbeam/server
  DOCKER_NETWORK: etherbeam-net

on:
  - workflow_dispatch

jobs:
  deploy-app:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Deploy Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ env.APP_PATH }}
            docker stop etherbeam_eth_server || true && docker rm etherbeam_eth_server || true
            docker stop etherbeam_server || true && docker rm etherbeam_server || true
            docker stop etherbeam_database || true && docker rm etherbeam_database || true
            docker-compose -f docker-compose.production.yml up -d
            install -d -m 770 -o deploy -g user ${{ env.APP_PATH }}/dump

      - name: Wait & check Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sleep 1m
            docker ps -a -f "network=${{ env.DOCKER_NETWORK }}" | grep Exited && exit 1 || exit 0
