name: Deploy build
env:
  APP_PATH: /var/app/etherbeam/server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy build
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Create .env file
        working-directory: ${{ env.SERVER_PATH }}
        run: |
          echo POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' > .env
          echo ETH_SERVER_USER_PASSWORD='${{ secrets.SERVER_API_PASSWORD }}' >> .env

      - name: Copy repository to the VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "${{ env.SERVER_PATH}}/*"
          target: "${{ env.APP_PATH }}"
          rm: false

      - name: Build Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd ${{ env.APP_PATH }}
            docker-compose -f docker-compose.production.yml build server
